### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by wangshaonan** [jihunchoi/unsupervised-treelstm#1]
python -m snli.train --help

Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 151, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name)
  File "/usr/lib/python3.4/runpy.py", line 126, in _get_module_details
    code = loader.get_code(mod_name)
  File "<frozen importlib._bootstrap>", line 1549, in get_code
  File "<frozen importlib._bootstrap>", line 1509, in source_to_code
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/snwang/syntax/unsupervised-treelstm-master/snli/train.py", line 25
    train_dataset: SNLIDataset = pickle.load(f)
                 ^
SyntaxError: invalid syntax

**Comment by wangshaonan** [comment]
what does the input data.pickle like, does it contain vocabulary, label and sentence length? is there a sample?

**Comment by jihunchoi** [comment]
The code is implemented in python 3.6, and it seems that you are using 3.4 now.
Some fancy statements are not available in former versions of python.
I recommend that you remove all statements from the newer version, such as variable annotation, f-strings, etc.

**Comment by jihunchoi** [comment]
And for the pickle files, I'm sorry for lack of documentation!
You can preprocess the data in the following process:
1) build the vocabulary file by executing `python -m [dataset].build_vocab ...`
2) dump the dataset using the output of 1) and the original dataset file.
3) train the model using the dump dataset (2).

**Comment by wangshaonan** [comment]
Thank you for reply. it works now.
